language: generic

os: linux
dist: xenial

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main"
        key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    packages:
      - powershell

before_script:
  - pwsh -Command 'Install-Module -Force -Scope CurrentUser Pester'

script:
  - pwsh -File ./build/run-tests.ps1

deploy:
  provider: script
  on:
    tags: true
  script: pwsh ./build/create-manifest.ps1 -Version $TRAVIS_TAG
